config/routes.rb
Rails.application.routes.draw do
  root 'devise/sessions#new'
  devise_for :users
  resources :login
  resources :users
  resources :users, only: [:show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, Post
    can :read, Comment
    return unless user.present?

    can :manage, Post, author: user
    can :manage, Comment, author: user

    return unless user.isadmin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  after_save :update_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).first(3)
  end

  def isadmin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    puts "comment params: #{comment_params}"
    @post = Post.find(params[:post_id] || params[:id])
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post = @post

    respond_to do |format|
      if @comment.save!
        format.html do
          redirect_to user_post_url(current_user, @post), notice: 'Comment was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = comment.post
    post_author = post.author
    if comment.destroy
      flash[:notice] = 'Comment was deleted successfully.'
      redirect_to user_post_path(post_author, post)
    else
      flash.now[:error] = 'Comment was not deleted.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
    @user = current_user
  end

  def create
    @post = Post.find(params[:post_id] || params[:id])
    @like = Like.new(post_id: @post.id, author_id: current_user.id)
    @like.author_id = current_user.id

    respond_to do |format|
      if @like.save
        format.html { redirect_to user_post_url(current_user, @post), notice: 'Like was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @form = User.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = current_user
    @posts = Post.where(author_id: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(title: params[:post][:title], text: params[:post][:text], comments_counter: 0, likes_counter: 0)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save!
        format.html { redirect_to new_user_post_url(current_user, @post), notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = 'Post was deleted successfully.'
      redirect_to user_posts_path(post.author)
    else
      flash.now[:error] = 'Post was not deleted.'
      render :show
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helpers.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section>
    <p class="post-title">Add New Comment :</p>
    <%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, class: "form-control" do |form| %>

    <div>
        <%= form.label :text %>
        <%= form.text_area :text, placeholder: "Type your comment here!", rows: 20, required: true,  class: "form-post-text" %>
    </div>

    <div>
        <%= form.submit "Save", class: "button" %>
    </div>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/likes/new.html.erb
<h3>Add New Like</h3>

<section>
    <%= form_with(model: @like, url: user_post_likes_path) do |form| %>
    <%= form.submit 'Add Like'%>
    <% end %>
</section>

app/views/login/index.html.erb
<div class="form">
    <h1>Login</h1>
    <%=form_for @form do |f| %>
        <div>
            <%= f.text_field :name, placeholder: "Usernama" %>
        </div>
        <div>
            <%= f.text_field :bio, placeholder: "Password" %>
        </div>
        <div>
            <%= link_to "login", users_path %>
        </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="posts">
    <img src="<%= @user.photo %>" alt="<%= @user.name %>" />
    <h1><%= @user.name %></h1>
    <h2><%= @user.bio %></h2>
    <p>Number of posts :<%= @user.posts_counter %></p>
    <%= link_to "Create new post", new_user_post_path(@user)  %>
    <% @posts.each do |post| %>
            <div class="schow_posts">
                <h3><%=post.title %></h3>
                <p><%=post.text %></p>
                <p>comment: <%=post.comments_counter %>
                <p>likes: <%=post.likes_counter %>
                <% post.recent_comments.each do |comment| %>
                    <%= button_to 'Delete comment', user_post_comment_path(comment.author, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>    
                    <p><%=comment.text %></p>
                <% end %>
                <%= button_to 'Delete comment', user_post_comment_path(comment.author, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>    
            </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<section>
    <p class="post-title">Add New Post :</p>
    <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class: "form-control" do |form| %>
        <%= form.hidden_field :comments_counter, value: 0 %>
        <%= form.hidden_field :likes_counter, value: 0 %>

        <div>
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Title", required: true, class: "form-post-title" %>
        </div>

        <div>
            <%= form.label :text %>
            <%= form.text_area :text, placeholder: "Type your post here!", rows: 20, required: true,  class: "form-post-text" %>
        </div>

        <div>
            <%= form.submit "Save"%>
        </div>
    <% end %>
</section>

app/views/posts/show.html.erb
<div class="see_post">
    <h3><%=@post.title %></h3>
    <p><%=@post.text %></p>
    <p><%=@post.author_id %></p>
    <p>comment: <%=@post.comments_counter %>
    <p>likes: <%=@post.likes_counter %>
    <% @post.recent_comments.each do |comment| %>
        <p><%= comment.author.name %> : <%= comment.text %></p>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="header">
    <h1>My Blog</h1>
</div>

<% @users.each do |user| %>
        <div class="user_container">
        <a href="<%= user_path(user.id) %>">
            <div class="user">
                <img src="<%= user.photo %>" alt="<%= user.name %>" />
                <div class="user_data">
                    <h1><%= link_to user.name, user %></h1>
                    <p>Number of posts: <%= user.posts_counter %></p>
                </div>
            </div>
        </a>
        </div>
<% end %>

app/views/users/show.html.erb
<div class="posts">
    <img src="<%= @user.photo %>" alt="<%=@user.name%>"/>
    <h1><%= @user.name %></h1>
    <h2><%= @user.bio %></h2>
    <p>Number of posts: <%= @user.posts_counter %></p>

    <% @user.posts.each do |post| %>
        <div class="schow_posts">
        <h3><%=post.title %></h3>
        <p><%=post.text %></p>
        <p>comment: <%=post.comments_counter %>
        <p>likes: <%=post.likes_counter %>
        </div>
    <% end %>
    <%= link_to user_posts_path(@user) do%>
        <button>See all posts</button>
    <% end %>
</div>